### ISSUE TITLE
All files inside Docs folder in v3.0.0-rc are zero byte

### ISSUE THREAD

**Issue by devopsokdone** [pubnub/dart#21]
It seems the documentation created with v3.0.0-rc is not working as all files are zero byte in Docs folder.

**Comment by are** [comment]
The documentation is working as it should, because its autogenerated by `dartdoc`. Those zero byte files in Docs are just stubs for categories inside the docs. If you want to generate docs locally, you have to run `dartdoc` in the PubNub SDK directory.

pub.dev is supposed to generate them, but for some reason it fails to do so: https://pub.dev/documentation/pubnub/3.0.0-rc/

**Comment by devopsokdone** [comment]
On pub.dev instead of documentation icon it says awaiting. So the link did not help.

But managed to create on local machine using dartdoc, thought the documentation is updated to include new things in V3.0.0-rc.1 but version number on top keeps showing as v2.0.1, just an observation.

**Comment by are** [comment]
Yeah, I have no idea why pub.dev doesn't want to generate the docs for that version.

It says v2.0.1 but that will be fixed once we release the v3.0.0.
